# Authors and contributors {-}

```{r setup, echo=FALSE, results="asis"}
library(rebook)
chapterPreamble()
```


### *Leo Lahti, DSc* {-}

Leo Lahti is professor in Data Science at the [Department of Computing, University of Turku, Finland](https://datascience.utu.fi/), with computational microbiome analysis as a key research area. Lahti obtained doctoral degree (DSc) from Aalto University in Finland (2010), developing probabilistic machine learning and data integration methods for high-throughput life science data. Since 2011 he switched to microbiome research and developed, among other things, the _phyloseq_-based [microbiome R package](https://bioconductor.org/packages/release/bioc/html/microbiome.html) before starting to develop the mia libraries and _TreeSummarizedExperiment_ / _MultiAssayExperiment_ framework for microbiome data science introduced in this gitbook. In addition to carrying out computational microbiome research, Lahti is in the editorial board of _ISME_ and _Microbiome_ journals, work group leader in the European COST action network [ML4microbiome](https://ml4microbiome.eu/), national delegate in the International Science Council Committee on Data ([CODATA](https://codata.org/)), and led the development of [national policy on open access to research methods in Finland](https://avointiede.fi/en/policies-materials/policies-open-science-and-research-finland/policy-open-research-data-and-methods). He is current member in the [Bioconductor Community Advisory Board](https://bioconductor.org/about/community-advisory-board/) and runs regular training workshops in microbiome data science.


### *Tuomas Borman* {-}

Tuomas Borman is a PhD researcher at the Department of Computing, University of Turku, and one of the key developers of the [mia package family](https://microbiome.github.io). He has helped to set up the base ecosystem of data containers, packages, and tutorials.


### *Giulio Benedetti, Research Assistant* {-}

Giulio Benedetti is a research assistant at the Department of Computing, University of Turku. His research interest is mostly related to Data Science. He has also helped to expand the SummarizedExperiment-based microbiome analyses to the Julia language and implemented the [MicrobiomeAnalysis.jl](https://github.com/JuliaTurkuDataScience/MicrobiomeAnalysis.jl) package.


### *Felix Ernst, PhD* {-}

Felic Ernst is among the first developers of R/Bioc methods for microbiome research based on the _SummarizedExperiment_ class and its derivatives.



### Contributors {-}


Some of the key contributors include:

- *Sudarshan Shetty, PhD*

- *Shigdel Rajesh, PhD*, 

- *Henrik Eckermann*, PhD 

- *Chouaib Benchraka*

- *Yağmur Şimşek* 

- *Artur Sannikov*

- *Basil Courbayre*

- *Jeba Akewak*

- *Himmi Lindgren*

- *Lu Yang*

The full list of contributors is available via [Github](https://github.com/microbiome/OMA/graphs/contributors).


We would also like to thank everyone who contributed to the R packages
supporting the _TreeSummarizedExperiment_ ecosystem for microbiome
research. These include but are not limited to: mia, miaViz, miaTime,
miaSim, philr, ANCOMBC, curatedMetagenomicData, scater, scuttle, and
other packages.



### Acknowledgments {-}

This work would not have been possible without the countless
contributions and interactions with other researchers, developers, and
users. We express our gratitude to the entire Bioconductor community
for developing this high-quality open research software repository for
life science analytics, continuously pushing the limits in emerging
fields [@Gentleman2004, @Huber2015]. The developers and contributors
of this online tutorial are listed in Chapter \@ref(contributors).

The base ecosystem of data containers, packages, and tutorials was set
up as a collaborative effort by Tuomas Borman, Yağmur Şimşek, Giulio
Benedetti, Felix Ernst, and [Leo Lahti](http://www.iki.fi/Leo.Lahti).

The work has been supported by the COST Action network on Statistical
and Machine Learning Techniques for Human Microbiome Studies
([ML4microbiome](https://www.ml4microbiome.eu/)) [@MorenoIndias2021].

The framework is based on the _TreeSummarizedExperiment_ data
container created by Ruizhu Huang and others
[@R_TreeSummarizedExperiment], and on the MultiAssayExperiment by
Marcel Ramos et al. [@Ramos2017]. The idea of using these containers
as a basis for microbiome data science was initially advanced by the
groundwork of Domenick Braccia, Héctor Corrada Bravo and others, and
subsequently brought together with other microbiome data science
developers [@Shetty2019].

Ample demonstration data resources have been made available as the
[curatedMetagenomicData](https://waldronlab.io/curatedMetagenomicData/)
project by Edoardo Pasolli, Lucas Schiffer, Levi Waldron and others
[@Pasolli2017] adding important support.
A number of other contributors have advanced the ecosystem
further, and will be acknowledged in the individual
packages, [pull
requests](https://github.com/microbiome/OMA/graphs/contributors),
[issues](https://github.com/microbiome/OMA/issues), and other work.

The work has drawn inspiration from many sources, most notably from
the work on _phyloseq_ by Paul McMurdie and Susan Holmes
[@McMurdie2013] who pioneered the work on rigorous and reproducible
microbiome data science ecosystems in R/Bioconductor. The phyloseq
framework continues to provide a vast array of complementary packages
and methods for microbiome studies, and we aim to support full
interoperability.

The open source books by Susan Holmes and Wolfgang Huber, Modern
Statistics for Modern Biology [@Holmes2019] and by Garret Grolemund
and Hadley Wickham, the R for Data Science [@Grolemund2017], and
Richard McElreath's Statistical Rethinking and the associated online
resources by Solomon Kurz [@McElreath2020] are key references that
advanced reproducible data science training and dissemination. The
Orchestrating Single-Cell Analysis with Bioconductor, or _OSCA_ book
by Robert Amezquita, Aaron Lun, Stephanie Hicks, and Raphael Gottardo
[@Amezquita2020natmeth] has implemented closely related work on the
_SummarizedExperiment_ data container and its derivatives in the field
of single cell sequencing studies. Many approaches used in this book
have been derived from the [OSCA
framework](https://bioconductor.org/books/release/OSCA/), with various
adjustments and extensions dedicated to microbiome data science.

