project:
  type: book

format: 
  html:
    theme:
      light: flatly
      dark: darkly

book:
# the next option enbale the reader-mode. It hides to TOC and the otpion seems the be automatically enabled by default on Chromium
  #reader-mode: true
  repo-actions: issue
  sidebar:
    border: true
    title: Orchestrating Microbiome Analysis with Bioconductor
    tools:
      - icon: twitter
      - icon: facebook
        href: https://microbiome.github.io/mia/

  # file with '#' are not used anymore
  # files with '##' are the one that need to be corrected 
  chapters:
  - index.qmd
  - 01_intro.qmd
  - 06_packages.qmd
  - 04_containers.qmd
  - 10_manipulation.qmd
  - 12_quality_control.qmd
  #- 11_taxonomic_information.qmd
  - 14_alpha_diversity.qmd
  - 20_beta_diversity.qmd
  - 21_microbiome_community.qmd
  #- 24_clustering.qmd
  - 30_differential_abundance.qmd
  - 40_machine_learning.qmd
  - 23_multi-assay_analyses.Rmd
  - 19_visualization_techniques.qmd
  - 80_training.qmd
  - 95_resources.qmd
  - 98_exercises.qmd
  - 97_extra_materials.qmd
  appendices :
    - 90_acknowledgments.qmd
    - Session_info.qmd
    - 99_bibliography.qmd

