### Differential abundance with visual comparisons

The packages _ALDEx2_, _ANCOM-BC_, _Maaslin2_ and _fido_, which were described in chapter \@ref(differential-abundance), support a number of visualization techniques that are specific to each. The **MA**, also called **Bland-Altman**, and the **MW** plots are characteristic of _ALDEx2_ and show difference in abundance among strains as a function of log-ratio abundance and dispersion, respectively. They both present differentially abundant taxa as red dots, uniformly abundant ones as gray dots and rarely abundant ones as black dots. In the case of _ANCOM-BC_ and _Maaslin2_, the analysis returns several **box plots** of the top differentially abundant experimental and control samples. Finally, the tree-based model produced by _fido_ measures the effect of each parameter in terms of its predicted influence on the variance of the selected variable.

|        | _ALDEx2_         | _ANCOM-BC_  | _Maaslin2_   | _fido_                |
|:------:|:----------------:|:-----------:|:------------:|:---------------------:|
| method | `aldex.plot`     | `ancombc`   | `Maaslin2`   | `pibble`, `plot`      |
| plots  | MA and MW plot   | box plot    | box plot     | effect plot           |