# Training {#sec-training}

```{r setup, echo=FALSE, results="asis"}
library(rebook)
chapterPreamble()
```

The page provides practical information to support training and self-study.


## Checklist {#sec-checklist}

Brief checklist to prepare for training (see below for links).

 * Install the recommended software
 * If the time allows, watch the short online videos and familiarize with the other available material
 * Join Gitter online chat for support


## Recommended software {#sec-software}

We recommend to install and set up the relevant software packages on
your own computer as this will support later use. The essential
components to install include:

* [R (the latest official release)](https://www.r-project.org/) 

* [RStudio](https://www.rstudio.com/products/rstudio/download/);
  choose "Rstudio Desktop" to download the latest version. Check the
  [Rstudio home page](https://www.rstudio.com/) for more
  information. RStudio is optional.

* Install key R packages (Section [@sec-packages] provides an installation script)


* After a successful installation you can consider trying out examples
  from Section [@sec-exercises] already before training. **You can run
  the workflows by simply copy-pasting examples.** You can then test
  further examples from this tutorial, modifying and applying these
  techniques to your own data. Plain source code for the individual chapters of this book are available via [Github](https://github.com/microbiome/OMA/tree/master/R)
  
* If you have access to CSC notebook  you can find instructions from [here](https://microbiome.github.io/course_2023_oulu/start.html#csc-notebook).


## Study material {#sec-material}

We encourage to familiarize with the material and test examples in advance but this is optional:

 * [Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/) (for beginners with R)
 
 * [Short online videos](https://www.youtube.com/playlist?list=PLjiXAZO27elAJEptP59BN3whVJ61XIkST) on microbiome data science with R/Bioconductor  

 * [Quarto presentations](https://microbiome.github.io/outreach/index.html)

 * [Orchestrating Microbiome Analysis with Bioconductor (OMA)](https://microbiome.github.io/OMA/) (this book)

 * [Other outreach material](https://github.com/microbiome/outreach)

 * @sec-exercises for self-study

 * @sec-resources and links to complementary external material



## Support and resources

For online support on installation and other matters, join us at
[Gitter](https://gitter.im/microbiome/miaverse?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

You are also welcome to connect through various channels with our
broader [developer and user community](https://microbiome.github.io).


## Further reading

The following online books provide good general data science background:

  * (Data science basics in R](https://r4ds.had.co.nz)
  * (Modern Statistics for Modern Biology)[https://www.huber.embl.de/msmb/] open access book (Holmes S, Huber W)
  * [The Bioconductor
    project](https://carpentries-incubator.github.io/bioc-project/)
    (background on the Bioconductor project; Carpentries workshop)



## Code of Conduct {#sec-coc}

We support the [Bioconductor Code of Conduct](https://bioconductor.github.io/bioc_coc_multilingual/). The community values an open approach to science that promotes 

  - sharing of ideas, code, software and expertise
  - a kind and welcoming environment, diversity and inclusivity
  - community contributions and collaboration

