# Function Reference {#sec-function-ref}

## Objects

| Function name                 | package                       | man page                          | link |
|---------------                |---------                      |-------------                      |------|
| `SingleCellExperiment`        | `SingleCellExperiment`        | `?SingleCellExperiment`           | [BioC](https://doi.org/doi:10.18129/B9.bioc.SingleCellExperiment) |
| `TreeSummarizedExperiment`    | `TreeSummarizedExperiment`    | `?TreeSummarizedExperiment`       | [BioC](https://doi.org/doi:10.18129/B9.bioc.TreeSummarizedExperiment) |

## Reduced dimension (PCA, t-SNE, UMAP, MDS, etc)

| Function name         | package                       | man page          | link |
|---------------        |---------                      |-------------      |------|
| `reducedDim`          | `SingleCellExperiment`        | `?reducedDims`    | [BioC](https://doi.org/doi:10.18129/B9.bioc.SingleCellExperiment) |
| `reducedDims`         | `SingleCellExperiment`        | `?reducedDims`    | [BioC](https://doi.org/doi:10.18129/B9.bioc.SingleCellExperiment) |
| `plotReducedDim`      | `scater`                      | `?plotReducedDim` | [BioC](https://doi.org/doi:10.18129/B9.bioc.scater) |

## Plotting

| Function name         | package                       | man page          | link                                                     |
|---                    |---                            |---                |---                                                       |
| `plotColData`         | `scater`                      | `?plotColData`    | [BioC](https://doi.org/doi:10.18129/B9.bioc.scater)      |
| `plotRowData`         | `scater`                      | `?plotRowData`    | [BioC](https://doi.org/doi:10.18129/B9.bioc.scater)      |
| `plotExpression`      | `scater`                      | `?plotExpression` | [BioC](https://doi.org/doi:10.18129/B9.bioc.scater)      |
| `plotReducedDim`      | `scater`                      | `?plotReducedDim` | [BioC](https://doi.org/doi:10.18129/B9.bioc.scater)      |
| `plotRowTree`         | `miaViz`                      | `?plotTree`       | [GitHub](https://github.com/microbiome/miaViz)           |
| `plotColTree`         | `miaViz`                      | `?plotTree`       | [GitHub](https://github.com/microbiome/miaViz)           |
| `plotRowGraph`        | `miaViz`                      | `?plotGraph`      | [GitHub](https://github.com/microbiome/miaViz)           |
| `plotColGraph`        | `miaViz`                      | `?plotGraph`      | [GitHub](https://github.com/microbiome/miaViz)           |
| `plotAbundance`       | `miaViz`                      | `?plotAbundance`  | [GitHub](https://github.com/microbiome/miaViz)           |
| `plotPrevalence`      | `miaViz`                      | `?plotPrevalence` | [GitHub](https://github.com/microbiome/miaViz)      |
| `plotSeries`          | `miaViz`                      | `?plotSeries`     | [GitHub](https://github.com/microbiome/miaViz)              |

