# Exercises {#sec-exercises}

```{r setup, echo=FALSE, results="asis"}
library(rebook)
chapterPreamble()
```

Here you can find assignments on different topics. For example solutions, see
[@exercises-solutions].

::: {.callout-tip}
## Tips for exercises

- Add clear comments explaining each line or section of code. This enhances
understanding for both you and others, aids in debugging, facilitates code
reuse, and promotes transparency.
- Interpret results by comparing them to existing literature. Summarize key
findings to ensure they are easily understandable, even for those without
advanced expertise in data analytics.
- Avoid hard-coding values. Instead, define variables at the start of the
code chunk to make parameter adjustments easier and improve code reusability.

:::

## Basics of R/Bioconductor

Bioconductor training material has been contributed to
[Carpentries](https://carpentries.org/). You can check the following lessons
for basic background of R and Bioconductor.

 * [Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/)

 * [Introduction to the Bioconductor project](https://carpentries-incubator.github.io/bioc-project/)

## Introduction

These exercises are related to [@sec-microbiome-in-bioconductor] and
[@sec-ecosystem].

### Introduction to Bioconductor

1. Go to [Bioconductor website](https://bioconductor.org/).
2. Navigate to "Packages" section.
3. Search for packages with the biocViews category "microbiome". How many
different packages are available?
4. Look up the mia package. What is its current version? Is it released or
devel version?
5. Locate the mia package's Reference Manual. When was it last updated?

### Reproducible reporting with Quarto

The following batch of exercises walks you through typical use cases of Quarto
in RStudio. Before heading to the exercises, it is recommended to read the
[Quarto guidelines for RStudio](https://quarto.org/docs/tools/rstudio.html)

#### New document

This exercise gets you started with creating a Quarto document and adding
text to it with typing conventions borrowed from the
[markdown syntax](https://quarto.org/docs/authoring/markdown-basics.html).
Feel free to render the document with the **Render** button after each step to
see the changes in the final report.

1. Open RStudio and create a new Quarto file named `My first Quarto`.
2. Add the subtitle `My first section` and write some text of your choice
underneath. You can choose the level of headings by the number of preceding
hashes (`#`).
3. Add a subsection named `List of items` and list three items underneath, both
ordered and unordered. You can initialize items with numbers (`1.`, `2.`,
`3.`, ...) or stars (`*`) for the ordered and unordered case, respectively.
4. Add another subsection named `Link to web` and add a clickable link to the
[OMA book](https://microbiome.github.io/OMA/), using the pattern
`[text](url)`.
5. Render the document and check its appearance

Nice start! You are now able to create a Quarto document, understand its syntax
and can render it into a reproducible report. If you got stuck, you can look up
the docs on
[creating](https://quarto.org/docs/tools/rstudio.html#creating-documents)
and [rendering](https://quarto.org/docs/tools/rstudio.html#render-and-preview)
Quarto documents.

#### Code chunks

While customizable text is nothing new by itself, the advantage of Quarto (and
previously Rmarkdown) is to combine text with code in R or other programming
languages, so that both the analytical pipeline and verbal description can be
put in one place. In this exercise, we learn how to write and run code in Quarto.

1. Open RStudio and create a new Quarto file (click on File tab - New File -
Quarto document).
2. Initialize a code chunk by pressing `alt` + `cmd` + `i` and define the
variables `A <- "my name"` and `B <- 0` in it.
3. Write the text `Below is my first code chunk` just above the code chunk.
4. Initialize one more code chunk and add 100 to the variable `B` in it.
5. Write the text `Below I change variable B` just above the second chunk.
6. **Extra**: Write the following line of text: `my name is A and I am B years old`, where A and B are variables defined in the code chunks upstream and change
if those variables are modified. Be aware that inline code can be added as
`> r my_inline_command` (without `>`).

Good job. You are now able to combine text and code in a Quarto document. If you
got stuck, you can refer to the Quarto docs on
[using code chunks](https://quarto.org/docs/visual-editor/technical.html#code-chunks).

#### Knitr options

Code chunks can be greatly customized in terms of visibility and execution,
output size and location and much more. This is possible with the knitr chunk
options, which usually appear at the beginning of the target chunk with the
syntax `#| option-name: value`, also described
[here](https://quarto.org/docs/computations/r.html#chunk-options).
In this exercise, we explore part of the knitr potential.

1. Open RStudio and create a new Quarto file.
2. Initialize three code chunks and label them as `setup`, `fig-box` and
`tbl-coldata`, respectively. Remember that the name of a chunk can be
specified with the `label` option.
3. Write the following code in the corresponding chunk and render the document.
4. Set `include: false` in the `setup` chunk, `fig-width: 10` in the `fig-box`
chunk and `echo: false` in the `tbl-coldata` chunk. Render the document again
and find the differences from before.

The setup code and output are no longer visible, resulting in a cleaner
document without initialization details. Figures in the fig-box chunk are now
wider, providing better visibility and detail in the graphics. The code in the
tbl-coldata chunk is hidden, making the document more concise and focused on
the results rather than the code implementation.

5. Add the options `fig-cap` and `tab-cap` to the `fig-box` and `tbl-coldata`
chunks, respectively. They require some text input, which makes for the
caption of the figures or tables.
6. **Extra**: Create a cross-reference to `fig-box` and `tbl-coldata` in the
text above the respective code chunk. You can do that with the syntax
`@chunk-name`.
7. **Extra**: Define a custom folder for storing figures with `fig-path`. Insert
it in `knitr::opts_chunk$set`, so that it applies globally to all the figures
generated in the document.

Congratulations! You are now familiar with the great potential and flexibility
of knitr chunk options. An exhaustive list of available options can be found
in the [knitr documentation](https://yihui.org/knitr/options/).

#### YAML instructions

The box at the beginning of every Quarto document contains yaml options that let
you define the metadata of the document. They will affect the appearance of the
document when it is rendered. By default, the box includes yaml options for the
title, format and editor to be used, but much more information on layout, code
execution and figures can be specified. A comprehensive list of yaml options is
available [here](https://quarto.org/docs/reference/formats/html.html). In this
exercise, we will get a tiny taste of such functionality.

1. Open RStudio and create a new Quarto file.
2. In the yaml box at the beginning of the document, change the title from
`Untitled` to `My first Quarto`.
4. In the same box, add the two lines `author` and `date` followed by your name
and today's date, respectively.
5. Render the document and check its appearance.
6. **Extra**: Set `toc: true` to produce a table of contents. This line should
follow `format` and `html` at the second level of indentation.

Well done! Now you are able to specify yaml options and understand how they
affect your Quarto document. If you got stuck, you can check
[this section](https://quarto.org/docs/tools/rstudio.html#yaml-intelligence) of
the Quarto documentation.

#### Quarto parameters

An advanced feature of Quarto consists of execution parameters, which are
externally pre-defined variables that are also accessible in the Quarto document.
They can be specified in the yaml box as `params`. Here we learn how to use them.

1. Open RStudio and create a new Quarto file.
2. In the yaml box at the beginning of the document, add a line named `params`
followed by an indented line with `gamma: 10`
3. Initialize a code chunk and type `str(params$gamma)` in it.
4. Render the document and check what happened.
5. Define one more parameter `beta: 3` and multiply `gamma` by `beta` in a code
chunk below.
6. Render the document again and check what happened.

Well done! You can now use an advanced feature of Quarto such as parameters.
If you got stuck,
[here](https://quarto.org/docs/computations/parameters.html#knitr)
you can find more information about parameter definition and usage.

## Data containers

These exercises are related to [@sec-containers].

### Assay retrieval

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. List the names of all available assays with `assayNames()`.

3. Fetch the list of assays with `assays()`.

4. Retrieve the first assay of the `TreeSE` with `assay()`, where the second
argument can be either the name or the index of the desired assay.

Well done! You can now locate and retrieve individual assays of a `TreeSE`. If
you got stuck, refer to chapter [@sec-assay-slot] of this book.

### Sample information

1. Import the `mia` package, load any of the example datasets mentioned in [@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Check the names of the samples with `colnames()`.

3. List the information on samples available in `colData` with `colnames()`.

4. Do the same now for the rows of `colData`. What these names correspond?

5. Visualize the `colData` with `View()` and briefly look at the information
stored in the different columns.

### Feature information

1. Import the `mia` package, load any of the example datasets mentioned in
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Check the names of the features with `rownames()`.

3. List the information on features available in `rowData` with `colnames()`.

4. Do the same now for the rows of `rowData`. What these names correspond?

5. Visualize the `rowData` with `View()` and briefly look at the information
stored in the different columns.

### Other elements

Extract some of the other `TreeSE` elements listed in chapter [@sec-containers].
However, note that such data are not always included.

1. Import the mia package, load any of the example datasets mentioned in
[@sec-example-data] and store it into a variable named `tse`.

2. Fetch the metadata of the `TreeSE`. Is there any information available?

3. Access the phylogenetic tree with `rowTree()`. How big is it in terms of tips
and nodes?

4. Check if a sample tree is available with `colTree()`, which is suitable for
hierarchical or nested study designs.

5. If present, obtain the information on feature DNA sequences from the
`referenceSeq` slot.

Useful functions:

`assayNames()`, `assays()`, `colData()`, `rowData()`,
`rownames()`, `colnames()`, `rowTree()`, `colTree()`, `referenceSeq()`

## Import

These exercises are related to [@sec-import].

### Construct `TreeSE`

1. Download the data

Fetch or download the CSV files from
[this directory](https://github.com/microbiome/data/tree/main/OKeefeDSData).

2. Load the data into R

Read the downloaded CSV files into R using `read.csv()` and store them in
the following variables:

   - `assay` → contains the main data matrix (e.g., microbial counts)
   - `rowdata` → contains metadata for features (e.g., taxonomic
   information)
   - `coldata` → contains metadata for samples (e.g., sample descriptions)

3. Convert data into correct format
    - `assay` → converted into a `matrix`
    - `rowdata` → converted into a `DataFrame`
    - `coldata` → converted into a `DataFrame`

4. Create a `SimpeList` containing the abundance table

5. Create a `TreeSummarizedExperiment` object

Use the `TreeSummarizedExperiment()` function to combine the datasets.

6. Verify the import

Ensure that the data has been correctly imported by checking that the
values in the `TreeSE` object match those in the original CSV files.
    - Pick a random row (feature) and column (sample).
    - Compare the corresponding value in the original assay data and the
    `TreeSE` object.

Useful functions:

`read.csv()`, `DataFrame()`, `TreeSummarizedExperiment()`, `matrix()`,
`rownames()`, `colnames()`, `SimpleList()`

## Convert & export

These exercises are related to [@sec-convert].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Convert data to `phyloseq` object.

3. Convert `phyloseq` data back to `TreeSE`.

4. Save `TreeSE` object.

5. Convert data to long format and save it as a CSV file.

Useful functions:

`convertToPhyloseq()`, `convertFromPhyloseq()`, `saveRDS()`, `meltSE()`,
`write.csv()`

## Taxonomic information

These exercises are related to [@sec-taxonomic-information].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Ensure that the data includes `rowData` and `rowTree`. If not, select some
other dataset.

3. List the available taxonomic ranks in the data with `taxonomyRanks()`.

4. List the unique taxa from specific taxonomy rank.

5. Subset data by taking, e.g., first 10 rows.

6. Prune the tree to correspond the subsetted data.

7. Visualize the phylogeny.

Useful functions:

`rowData()`, `rowTree()`, `taxonomyRanks()`, `getUnique()`, `subsetByLeaf()`,
`plotRowTree()`

## Data wrangling

These exercises are related to [@sec-datawrangling].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Explore sample metadata.

3. Add column to `colData`. You can choose column name and the values. E.g.,
you can add values from random normal distribution (`rnorm`()`) to column
"value".

4. Load second dataset and merge it with the first one.

5. Select categorical value and split the data.

Useful functions:

`colData()`, `rnorm`()`, `mergeSEs()`, `splitOn()`

## Subsetting

These exercises are related to [@sec-treese_subsetting].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Calculate library sizes.

3. Explore `colData`. Subset samples that exceed specific library size threshold.

4. Subset data by selecting only prevalent features.

Useful functions:

`addPerCellQCMetrics()`, `colData`()`, `subsetByPrevalent()`

## Agglomeration

These exercises are related to [@sec-agglomeration].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. List the available taxonomic ranks in the data with `taxonomyRanks()`.

3. Agglomerate data to single rank and save the new data to variable called `tse_agglomerated`.

4. Observe `rowData` of agglomerated data. What has happened? Why there are so
many `NA`s?

5. Agglomerate data to all taxonomy ranks at once.

6.Explore the agglomerated data in `altExp` slot.

7. Agglomerate the data based on prevalence and save the new data to variable
called `tse_agglomerated`.

8. Add `tse_agglomerated` to `altExp` slot of the original `TreeSE` object.

9. Explore `colData`. Select some grouping variable and agglomerate the data on
the groups. Save the agglomerated data to variable called `tse_agglomerated`.

Useful functions:

`taxonomyRanks()`, `agglomerateByRank`()`, `rowData()`, `agglomerateByRanks()`,
`altExpNames()`, `altExp()`, `agglomerateByPrevalence()`, `altExp()<-`,
`colData()`, `agglomerateByVariable()`

## Transformation

These exercises are related to [@sec-assay-transform].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Transform the counts assay into relative abundances and store it into the
`TreeSE` as an assay named `relabund`.

3. Similarly, perform a clr transformation on the counts assay with a
`pseudocount` of 1 and add it to the `TreeSE` as a new assay.

4. List the available assays by name.

5. Access the clr assay and store it to variable called `mat`. Select a subset
of its first 100 features and 10 samples, and print the abundance table. Explore
the data.

6. Agglomerate the data with `agglomerateByRanks()` Tranform data now with
`altexp = altExpNames(tse)`.

6. **Extra**: If the data has phylogenetic tree, perform the phILR
transformation.

Useful functions:

`transformAssay()`, `assayNames()`, `assay()`, `agglomerateByRanks()`

## Exploration & quality control

These exercises are related to [@sec-quality-control].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Summarize the counts with with histogram.

3. Add prevalence of taxa to `rowData`.

4. Visualize the prevalence distribution with histogram.

5. Add library sizes to `colData`.

6. Visualize the library size distribution with histogram.

7. Calculate a table that summarizes the dominance.

8. Get the most prevalent features.

9. Get the most abundant features based on median abundance. How this differs
from prevalent features?

9. Visualize the most prevalent features.

Useful functions:

`plotHistogram()`, `addPrevalence()`, `rowData()`, `addPerCellQCMetrics()`,
`colData()`, `summarizeDominance()`, `getPrevalent()`, `getTop`,
`plotAbundanceDensity()`

## Community composition

These exercises are related to [@sec-microbiome-community].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Agglomerate data to phylum level.

3. Transform data to relative abundances.

4. Visualize community with relative abundance bar plot.

6. Explore `colData`. Select sample metadata variable and visualize the
composition with bar plot in respect to sample grouping.

7. Apply Z-transform, i.e, standardization.

8. Plot z-transformed abundances with heatmap.

Useful functions:

`agglomerateByRank()`, `transformAssay()`, `plotAbundance()`,
`colData()`, `sechm::sechm()`

## Alpha Diversity

These exercises are related to [@sec-alpha-diversity].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Calculate Shannon diversity index, and add the results to `colData()`.

3. Observe `colData`, especially its column names.

4. Summarize the distribution of Shannon diversity with histogram.

5. Calculate Shannon diversity index with rarefaction and store it to `colData`
as column "shannon_rarefaction".

6. Calculate correlation between Shannon indices, with and without rarefaction.

7. Visualize the correlation.

8. Calculate all available indices.

9. Visualize single diversity index in respect to some sample grouping that you
can find from `colData`.

10. Calculate statistical significance of difference in selected alpha diversity
index between the sample groups.

11. Interpret results.

Useful functions:

`addAlpha()`, `plotHistogram()`, `getCrossAssociation()`,
`scater::plotColData()`, `stats::wilcox.test()`,
`stats::pairwise.wilcox.test()`, `stats::kruskal.test()`

## Community similarity

These exercises are related to [@sec-community-similarity].

Your task is to get insights on the community and its relation to sample groups.

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

2. Apply CLR transformation.

3. Apply Principal Component analysis (PCA).

4. List all available reduced dimensionalities in `reducedDim` slot.

5. Retrieve PCA results from `reducedDim` slot, and explore them.

8. Visualize first two principal components.

9. Visualize PCA loadings.

10. Apply relative transformation.

11. Apply Principal Coordinate Analysis (PCoA) to relative abundances with
Bray-Curtis dissimilarity.

12. List again all available reduced dimensionalities in `reducedDim` slot.

13. Visualize PCoA results.

14. Run PCoA with rarefaction. Visualize the results and compare them to PCoA
without rarefaction. Do the plots look similar?

15. Explore `colData`. Select sample metadata variables and run distance-based
redundancy analysis (db-RDA) to relative abundances with Bray-Curtis
dissimilarity.

16. Explore the statistical significance of the results.

17. Visualize the db-RDA results.

Useful functions:

`transformAssay()`, `scater::runPCA()`, `reducedDimNames()`, `reducedDim()`
`scater::plotReducedDim()`, `plotLoadings()`, `addMDS()`, `addRDA()`,
`getReducedDimAttribute()`, `plotRDA()`

## Community typing

These exercises are related to [@sec-clustering].

1. Import the mia package, load any of the example datasets mentioned in 
[@sec-example-data] with `data()`, and store it into a variable named `tse`.

## Differential abundance

These exercises are related to [@sec-differential-abundance].

## Correlation

These exercises are related to [@sec-correlation].

## Mediation

These exercises are related to [@sec-mediation].

## Network learning & analysis

These exercises are related to [@sec-network-learning].

## Network comparison

These exercises are related to [@sec-network-comparison].

## Cross-association

These exercises are related to [@sec-cross-correlation].

## Ordination-based multiassay analysis

These exercises are related to [@sec-multiassay_ordination].

## Multi-omics prediction and classification

These exercises are related to [@sec-multi-omics-integration].

## Machine learning

These exercises are related to [@sec-machine_learning].
