# Mediation {#sec-mediation}

what is the goal of mediation analysis?

```{r}
library(mia)
library(scater)

# Load dataset
data(hitchip1006, package = "miaTime")
tse <- hitchip1006
```

```{r}
# Agglomerate features by family (merely to speed up execution)
tse <- agglomerateByRank(tse, rank = "Phylum")
# Convert BMI variable to numeric
tse$bmi_group <- as.numeric(tse$bmi_group)
```

## Feature mediation

```{r}
# Analyse mediated effect of nationality on BMI via alpha diversity
# 100 permutations were done to speed up execution, but ~1000 are recommended 
med_df <- getMediation(tse,
                       outcome = "bmi_group",
                       treatment = "nationality",
                       mediator = "diversity",
                       covariates = c("sex", "age"),
                       treat.value = "Scandinavia",
                       control.value = "CentralEurope",
                       boot = TRUE, sims = 100,
                       add.metadata = TRUE)
 
# Visualise model statistics for 1st mediator
plot(attr(med_df, "metadata")[[1]])
```

what is the meaning of ACME, ADE and total effect?

## Assay mediation

```{r}
# Apply clr transformation to counts assay
tse <- transformAssay(tse,
                      method = "clr",
                      pseudocount = 1)

# Analyse mediated effect of nationality on BMI via clr-transformed features
# 100 permutations were done to speed up execution, but ~1000 are recommended     
tse <- addMediation(tse, name = "assay_mediation",
                    outcome = "bmi_group",
                    treatment = "nationality",
                    assay.type = "clr",
                    covariates = c("sex", "age"),
                    treat.value = "Scandinavia",
                    control.value = "CentralEurope",
                    boot = TRUE, sims = 100,
                    p.adj.method = "fdr")

# Show results for first 5 mediators
head(metadata(tse)$assay_mediation, 5)
```

```{r}
my_df <- metadata(tse)$assay_mediation

coef_mat <-  as.matrix(my_df[ , c("ACME_estimate", "ADE_estimate")])
p_mat <-  as.matrix(my_df[ , c("ACME_pval", "ADE_pval")])

rownames(coef_mat) <- my_df[["Mediator"]]
colnames(coef_mat) <- gsub("_estimate", "", colnames(coef_mat))

p_mat <- t(p_mat)

Heatmap(t(coef_mat),
        name = "Effect",
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        row_names_side = "left",
        column_names_rot = 45,
        rect_gp = gpar(col = "white", lwd = 2),
        cell_fun = function(j, i, x, y, w, h, fill) {
          if(p_mat[i, j] < 0.001) {
            grid.text("***", x, y)
          } else if(p_mat[i, j] < 0.01) {
            grid.text("**", x, y)
          } else if(p_mat[i, j] < 0.05) {
            grid.text("*", x, y)
          }
        })
```


## Mediation of reduced dimensions

```{r}
# Perform ordination
tse <- runMDS(tse, name = "MDS",
              method = "euclidean",
              assay.type = "clr",
              ncomponents = 5)

# Analyse mediated effect of nationality on BMI via MDS components 
# 100 permutations were done to speed up execution, but ~1000 are recommended       
tse <- addMediation(tse, name = "reddim_mediation",
                    outcome = "bmi_group",
                    treatment = "nationality",
                    dimred = "MDS",
                    covariates = c("sex", "age"),
                    treat.value = "Scandinavia",
                    control.value = "CentralEurope",
                    boot = TRUE, sims = 100,
                    p.adj.method = "fdr")

# Show results for first 5 mediators
head(metadata(tse)$reddim_mediation, 5)
```
```{r}
my_df <- metadata(tse)$reddim_mediation

coef_mat <-  as.matrix(my_df[ , c("ACME_estimate", "ADE_estimate")])
p_mat <-  as.matrix(my_df[ , c("ACME_pval", "ADE_pval")])

rownames(coef_mat) <- my_df[["Mediator"]]
colnames(coef_mat) <- gsub("_estimate", "", colnames(coef_mat))

p_mat <- t(p_mat)

Heatmap(t(coef_mat),
        name = "Effect",
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        row_names_side = "left",
        column_names_rot = 45,
        rect_gp = gpar(col = "white", lwd = 2),
        cell_fun = function(j, i, x, y, w, h, fill) {
          if(p_mat[i, j] < 0.001) {
            grid.text("***", x, y)
          } else if(p_mat[i, j] < 0.01) {
            grid.text("**", x, y)
          } else if(p_mat[i, j] < 0.05) {
            grid.text("*", x, y)
          }
        })
```

```{r}
reddim_mediation <- attr(metadata(tse)$reddim_mediation, "metadata")

plots <- lapply(reddim_mediation, plot)

#entries <- c("d.avg", "d.avg.p", "z.avg", "z.avg.p", "tau.coef", "tau.p")

#my_ls <- lapply(reddim_mediation, function(x) x[names(x) %in% entries])

#my_df <- data.frame(do.call(rbind, my_ls))


```

