<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>24&nbsp; Machine learning – Orchestrating Microbiome Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../pages/training.html" rel="next">
<link href="../pages/integrated_learner.html" rel="prev">
<link href="../assets/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-a14e345711173c227b21482e2eb4cc70.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6d7e0e055978adcb0dc3bbe98a6d8351.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-a14e345711173c227b21482e2eb4cc70.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-03a414507d0a5050258c27957027fec2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-393bbc8479d1addcfcd69448d6fb8193.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-03a414507d0a5050258c27957027fec2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar docked nav-fixed slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/mia_logo.png" alt="" class="navbar-logo light-content"><img src="../assets/mia_logo.png" alt="" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Orchestrating Microbiome Analysis</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bi-github">
<li>
    <a class="dropdown-item" href="https://github.com/microbiome/OMA/">
 <span class="dropdown-text">Source Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://microbiome.github.io/OMA/docs/devel/">
 <span class="dropdown-text">Browse version <code>devel</code></span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../pages/machine_learning.html">Machine learning &amp; statistical modeling</a></li><li class="breadcrumb-item"><a href="../pages/machine_learning.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Machine learning</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Microbiome data science in Bioconductor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/miaverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">miaverse</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Data containers &amp; importing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/containers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data containers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Import</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/convert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Convert &amp; export</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Data wrangling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/taxonomy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxonomic information</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data wrangling</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../pages/preprocess.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QC &amp; preprocessing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploration &amp; quality control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/subsetting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Subsetting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/agglomeration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Agglomeration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/transformation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Transformation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Diversity &amp; similarity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/composition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Community composition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/alpha_diversity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alpha diversity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/community_similarity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Community similarity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Community typing</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Association</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/differential_abundance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Differential abundance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/network_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Network learning &amp; analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/network_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Network comparison</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../pages/multiomics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-omics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/cross_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Cross-association</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/multiassay_ordination.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Ordination-based multiassay analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/integrated_learner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Multi-omics prediction and classification</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Machine learning &amp; statistical modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/machine_learning.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Machine learning</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Training</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Training</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Exercises</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Support &amp; resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Support</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Resources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/contributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Contributions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/msea.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Microbe Set Enrichment Analysis (MSEA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/mmuphin_meta_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Meta-analyses</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/extra_daa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Differential abundance analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/phyloseq_cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">phyloseq vs TreeSE cheatsheet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/example_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Example solutions for exercises</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/session_info.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Technical info</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background"><span class="header-section-number">24.1</span> Background</a>
  <ul class="collapse">
<li><a href="#unsupervised-machine-learning" id="toc-unsupervised-machine-learning" class="nav-link" data-scroll-target="#unsupervised-machine-learning"><span class="header-section-number">24.1.1</span> Unsupervised machine learning</a></li>
  <li><a href="#supervised-machine-learning" id="toc-supervised-machine-learning" class="nav-link" data-scroll-target="#supervised-machine-learning"><span class="header-section-number">24.1.2</span> Supervised machine learning</a></li>
  </ul>
</li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">24.2</span> Setup</a></li>
  <li>
<a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing"><span class="header-section-number">24.3</span> Data preprocessing</a>
  <ul class="collapse">
<li><a href="#preprocess-for-classification-task" id="toc-preprocess-for-classification-task" class="nav-link" data-scroll-target="#preprocess-for-classification-task"><span class="header-section-number">24.3.1</span> Preprocess for classification task</a></li>
  <li><a href="#preprocess-for-regression-task" id="toc-preprocess-for-regression-task" class="nav-link" data-scroll-target="#preprocess-for-regression-task"><span class="header-section-number">24.3.2</span> Preprocess for regression task</a></li>
  </ul>
</li>
  <li>
<a href="#model-training" id="toc-model-training" class="nav-link" data-scroll-target="#model-training"><span class="header-section-number">24.4</span> Model training</a>
  <ul class="collapse">
<li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest"><span class="header-section-number">24.4.1</span> Random forest</a></li>
  <li><a href="#xgboost" id="toc-xgboost" class="nav-link" data-scroll-target="#xgboost"><span class="header-section-number">24.4.2</span> XGBoost</a></li>
  </ul>
</li>
  <li>
<a href="#model-performance-metrics" id="toc-model-performance-metrics" class="nav-link" data-scroll-target="#model-performance-metrics"><span class="header-section-number">24.5</span> Model performance metrics</a>
  <ul class="collapse">
<li><a href="#classification-metrics" id="toc-classification-metrics" class="nav-link" data-scroll-target="#classification-metrics"><span class="header-section-number">24.5.1</span> Classification metrics</a></li>
  <li><a href="#regression-metrics" id="toc-regression-metrics" class="nav-link" data-scroll-target="#regression-metrics"><span class="header-section-number">24.5.2</span> Regression metrics</a></li>
  </ul>
</li>
  <li>
<a href="#visualizing-models-performance" id="toc-visualizing-models-performance" class="nav-link" data-scroll-target="#visualizing-models-performance"><span class="header-section-number">24.6</span> Visualizing model’s performance</a>
  <ul class="collapse">
<li><a href="#classification" id="toc-classification" class="nav-link" data-scroll-target="#classification"><span class="header-section-number">24.6.1</span> Classification</a></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">24.6.2</span> Regression</a></li>
  </ul>
</li>
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation"><span class="header-section-number">24.7</span> Model interpretation</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../pages/machine_learning.html">Machine learning &amp; statistical modeling</a></li><li class="breadcrumb-item"><a href="../pages/machine_learning.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Machine learning</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-machine_learning" class="quarto-section-identifier"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Machine learning</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="cell" data-layout-align="center">
<script>
document.addEventListener("click", function (event) {
    if (event.target.classList.contains("rebook-collapse")) {
        event.target.classList.toggle("active");
        var content = event.target.nextElementSibling;
        if (content.style.display === "block") {
            content.style.display = "none";
        } else {
            content.style.display = "block";
        }
    }
})
</script><style>
.rebook-collapse {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.rebook-content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: #f1f1f1;
}
</style>
</div>
<section id="background" class="level2" data-number="24.1"><h2 data-number="24.1" class="anchored" data-anchor-id="background">
<span class="header-section-number">24.1</span> Background</h2>
<p>Machine learning (ML) is a branch of artificial intelligence. While there are several definitions of machine learning, they generally involve using computational methods (i.e., machines) to identify patterns in data (i.e., learning).</p>
<p>Machine learning can be divided into supervised and unsupervised learning. Supervised ML is used to predict outcomes based on labeled data, whereas unsupervised ML is used to discover unknown patterns and structures within the data.</p>
<section id="unsupervised-machine-learning" class="level3" data-number="24.1.1"><h3 data-number="24.1.1" class="anchored" data-anchor-id="unsupervised-machine-learning">
<span class="header-section-number">24.1.1</span> Unsupervised machine learning</h3>
<p>“Unsupervised” means that the outcomes (e.g., patient status) are not known by the model during its training, and patterns are learned based solely on the data, such as an abundance table.</p>
<p>Common tasks in unsupervised machine learning include dimension reduction and clustering, tasks discussed in <a href="community_similarity.html" class="quarto-xref"><span>Chapter 14</span></a> and <a href="clustering.html" class="quarto-xref"><span>Chapter 15</span></a>, respectively.</p>
</section><section id="supervised-machine-learning" class="level3" data-number="24.1.2"><h3 data-number="24.1.2" class="anchored" data-anchor-id="supervised-machine-learning">
<span class="header-section-number">24.1.2</span> Supervised machine learning</h3>
<p>“Supervised” means that a model is trained on observations paired with a known output (e.g., patient status: healthy or diseased). During training, the model learns patterns from a portion of the data and it is then evaluated on its ability to generalize to new data. This process involves splitting the collected data into a training and testing sets, commonly in 80/20 ratio, although other proportions can be used depending on the size and applications of the dataset.</p>
<p>Training is usually enhanced with cross-validation to improve the model’s robustness. However, when the dataset is small, splitting it into training and test sets might not be feasible. In such cases, cross-validation alone can be used to provide a rough estimate of the model’s performance. This strategy involves dividing the data into K folds (or subsets) of similar size. The model is then trained on K-1 folds, and tested on the remaining fold. This process is repeated K times, allowing each fold to serve as the test set once. While this approach is not as reliable as having a separate test set, it can still give valuable insights into how well the model might perform on new data.</p>
<p>Common tasks for supervised machine learning includes classification (e.g., predict categorical variables) and regression (e.g., predicting continuous variables). This chapter discusses two supervised ML algorithms that can be applied to classification and regression tasks.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: ML in multi-omics data analysis
</div>
</div>
<div class="callout-body-container callout-body">
<p>ML applications for the integration of multi-omic datasets are covered in <a href="multiassay_ordination.html" class="quarto-xref"><span>Chapter 22</span></a> and <a href="integrated_learner.html" class="quarto-xref"><span>Chapter 23</span></a></p>
</div>
</div>
</section></section><section id="setup" class="level2 page-columns page-full" data-number="24.2"><h2 data-number="24.2" class="anchored" data-anchor-id="setup">
<span class="header-section-number">24.2</span> Setup</h2>
<p>Published fecal microbiome data <span class="citation" data-cites="qin2012_t2d">(<a href="#ref-qin2012_t2d" role="doc-biblioref">Qin et al. 2012</a>)</span> will be used to illustrate how to deploy supervised machine learning algorithms to address classification and regression problems. For classification, two ML models will be used to classify subjects in two groups: Type II diabetes patients or Healthy individuals (encoded as T2D and healthy in the metadata). For regression, models will be use to predict the body mass index (BMI) of each subject. In both tasks the models will be trained with participants gut microbiome data.</p>
<div class="no-row-height column-margin column-container"><div id="ref-ridaura2013_obesityFMT" class="csl-entry" role="listitem">
Ridaura, Vanessa K., Jeremiah J. Faith, Federico E. Rey, Jiye Cheng, Alexis E. Duncan, Andrew L. Kau, Nicholas W. Griffin, et al. 2013. <span>“Gut Microbiota from Twins Discordant for Obesity Modulate Metabolism in Mice.”</span> <em>Science</em> 341 (6150): 1241214. <a href="https://doi.org/10.1126/science.1241214">https://doi.org/10.1126/science.1241214</a>.
</div></div><p>Mounting evidence show associations between gut microbiome and the onset of type II diabetes. Thus, it has been suggested that microbiome data could be used to discriminate between patients and healthy individuals. Indeed, that hypothesis was explored in the research article where the dataset we will work with was released <span class="citation" data-cites="qin2012_t2d">(<a href="#ref-qin2012_t2d" role="doc-biblioref">Qin et al. 2012</a>)</span>. On the other hand, experiments conducted with twins have shown that while the transplantation of gut microbiome from the obese twin induces obesity in mice, the gut microbiome of the lean twin doesn’t <span class="citation" data-cites="ridaura2013_obesityFMT">(<a href="#ref-ridaura2013_obesityFMT" role="doc-biblioref">Ridaura et al. 2013</a>)</span>. Thus, predicting the health status of a person or their BMI from their gut microbiome seems a plausible task, and an interesting opportunity to learn about supervised ML algorithms using real-world data.</p>
<p>To do so, the R package <em><a href="https://CRAN.R-project.org/package=mikropml">mikropml</a></em> <span class="citation" data-cites="topcuoglu2020 topcuoglu2021">(<a href="#ref-topcuoglu2020" role="doc-biblioref">Topçuoğlu et al. 2020</a>, <a href="#ref-topcuoglu2021" role="doc-biblioref">2021</a>)</span> will be used throughout this chapter. This package was developed to offer a user-friendly interface to supervised ML algorithms implemented in the <em><a href="https://CRAN.R-project.org/package=caret">caret</a></em> package. <a href="https://www.schlosslab.org/mikropml/articles/introduction.html#the-methods-we-support">Here</a> is a list of models supported by <em><a href="https://CRAN.R-project.org/package=mikropml">mikropml</a></em>.</p>
<div class="no-row-height column-margin column-container"><div id="ref-topcuoglu2020" class="csl-entry" role="listitem">
Topçuoğlu, Begüm D., Nicholas A. Lesniak, Mack T. Ruffin, Jenna Wiens, and Patrick D. Schloss. 2020. <span>“A Framework for Effective Application of Machine Learning to Microbiome-Based Classification Problems.”</span> <em>mBio</em> 11 (3): 10.1128/mbio.00434–20. <a href="https://doi.org/10.1128/mbio.00434-20">https://doi.org/10.1128/mbio.00434-20</a>.
</div><div id="ref-topcuoglu2021" class="csl-entry" role="listitem">
Topçuoğlu, Begüm D., Zena Lapp, Kelly L. Sovacool, Evan Snitkin, Jenna Wiens, and Patrick D. Schloss. 2021. <span>“<span class="nocase">mikropml</span>: User-Friendly r Package for Supervised Machine Learning Pipelines.”</span> <em>Journal of Open Source Software</em> 6 (61): 3073. <a href="https://doi.org/10.21105/joss.03073">https://doi.org/10.21105/joss.03073</a>.
</div></div><p>The code below will retrieve the data and show the number of participants on each category.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/waldronlab/curatedMetagenomicData">curatedMetagenomicData</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">samples</span> <span class="op">&lt;-</span> <span class="va">sampleMetadata</span><span class="op">[</span><span class="va">sampleMetadata</span><span class="op">[[</span><span class="st">"study_name"</span><span class="op">]</span><span class="op">]</span> <span class="op">==</span> <span class="st">"QinJ_2012"</span>, <span class="op">]</span></span>
<span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/curatedMetagenomicData/man/returnSamples.html">returnSamples</a></span><span class="op">(</span></span>
<span>    <span class="va">samples</span>,</span>
<span>    dataType <span class="op">=</span> <span class="st">"relative_abundance"</span>,</span>
<span>    counts <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># use counts instead of rel abundances</span></span>
<span>    rownames <span class="op">=</span> <span class="st">"short"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Change assay's name to reflect its content</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assayNames</a></span><span class="op">(</span><span class="va">tse</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"counts"</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">tse</span><span class="op">[[</span><span class="st">"disease"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">T2D</th>
<th style="text-align: right;">healthy</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">170</td>
<td style="text-align: right;">193</td>
</tr></tbody>
</table>
</div>
</div>
</section><section id="data-preprocessing" class="level2 page-columns page-full" data-number="24.3"><h2 data-number="24.3" class="anchored" data-anchor-id="data-preprocessing">
<span class="header-section-number">24.3</span> Data preprocessing</h2>
<p>Before applying any ML algorithm, the data must be preprocessed. This speeds up the training of the models by reducing the amount of features analysed, a desirable outcome when working with high-dimensional microbiome data. In addition to faster performance, common pre-processing steps have biological justifications. For instance:</p>
<ul>
<li>
<strong>Collapse highly correlated features:</strong> In a microbial community, it’s common for the abundance of two or more taxonomic features to be highly correlated due to ecological interactions. Thus, removing or collapsing correlated features allows the model to analyse them as one group.</li>
<li>
<strong>Remove features with near-zero variance:</strong> Features that don’t vary enough across groups can hardly help in discerning between them, as they don’t hold any biologically relevant information. Additionally, under certain data splits, these variables can show zero variance.</li>
<li>
<strong>Remove features with low prevalence:</strong> Microbiome data is sparse, and taxonomic features present in just a few samples of each group hardly provide useful biological information for their classification.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Important: Data leakage is a common pitfall.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data leakage occurs when information from the test set influences the model training process, leading to overly optimistic performance estimates. This can happen, for example, if preprocessing steps like scaling are applied to both the training and test data together, allowing the model to indirectly “see” the test data during training. Fortunately, there are questions we can ask ourselves to void data leakage <span class="citation" data-cites="bernett2024_dataLeakage">(<a href="#ref-bernett2024_dataLeakage" role="doc-biblioref">Bernett et al. 2024</a>)</span></p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-bernett2024_dataLeakage" class="csl-entry" role="listitem">
Bernett, Judith, David B. Blumenthal, Dominik G. Grimm, Florian Haselbeck, Roman Joeres, Olga V. Kalinina, and Markus List. 2024. <span>“Guiding Questions to Avoid Data Leakage in Biological Machine Learning Applications.”</span> <em>Nature Methods</em> 21 (8): 1444–53. <a href="https://doi.org/10.1038/s41592-024-02362-y">https://doi.org/10.1038/s41592-024-02362-y</a>.
</div></div><p>The code below shows how to obtain the relative abundances of each taxonomic feature with different alpha diversity indices that provide ecosystem-level information. See <a href="alpha_diversity.html" class="quarto-xref"><span>Chapter 13</span></a> for a discussion on alpha diversity.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://microbiome.github.io/mia/">mia</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Keep taxa present in more than 10% of samples</span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://microbiome.github.io/mia/reference/getPrevalence.html">subsetByPrevalent</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"counts"</span>,</span>
<span>    prevalence <span class="op">=</span> <span class="fl">10</span> <span class="op">/</span> <span class="fl">100</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Transform to relative abundances</span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://microbiome.github.io/mia/reference/transformAssay.html">transformAssay</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"counts"</span>,</span>
<span>    method <span class="op">=</span> <span class="st">"relabundance"</span>,</span>
<span>    MARGIN <span class="op">=</span> <span class="st">"cols"</span>,</span>
<span>    pseudocount <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Alpha diversity indices to be calculated</span></span>
<span><span class="va">alpha_divs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"dbp_dominance"</span>,</span>
<span>    <span class="st">"faith_diversity"</span>,</span>
<span>    <span class="st">"observed_richness"</span>,</span>
<span>    <span class="st">"shannon_diversity"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Add alpha diversity indices to the metadata for latter use in our ML tasks</span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://microbiome.github.io/mia/reference/addAlpha.html">addAlpha</a></span><span class="op">(</span></span>
<span>    <span class="va">tse</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"counts"</span>,</span>
<span>    index <span class="op">=</span> <span class="va">alpha_divs</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="preprocess-for-classification-task" class="level3" data-number="24.3.1"><h3 data-number="24.3.1" class="anchored" data-anchor-id="preprocess-for-classification-task">
<span class="header-section-number">24.3.1</span> Preprocess for classification task</h3>
<p>Next, we join the outcome of interest (i.e, diagnosis status or BMI) of each participant with the microbiome abundances and alpha diversities. The resulting dataset will be preprocessed for its later use to train and test our model in the following section.</p>
<p>The code below shows how to preprocess our data for a classification task.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.schlosslab.org/mikropml/">mikropml</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preprocess data for classification</span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/preprocess_data.html">preprocess_data</a></span><span class="op">(</span></span>
<span>    dataset <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"disease"</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"relabundance"</span>,</span>
<span>    name <span class="op">=</span> <span class="st">"prep_classification"</span>,</span>
<span>    col.var <span class="op">=</span> <span class="va">alpha_divs</span>, <span class="co"># preprocess these metadata variables too</span></span>
<span>    remove_var <span class="op">=</span> <span class="st">"zv"</span>,</span>
<span>    collapse_corr_feats <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    group_neg_corr <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Identify the discarded features (that won't be used as predictors)</span></span>
<span><span class="va">prep_classification</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/altExps.html">altExp</a></span><span class="op">(</span><span class="va">tse</span>, <span class="st">"prep_classification"</span><span class="op">)</span></span>
<span><span class="va">removed_feats</span> <span class="op">&lt;-</span> <span class="fu">metadata</span><span class="op">(</span><span class="va">prep_classification</span><span class="op">)</span><span class="op">[[</span><span class="st">"removed_feats"</span><span class="op">]</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># If any alpha diversity index was removed, it will be discarded</span></span>
<span><span class="co"># from the predictors</span></span>
<span><span class="va">alpha_divs_classification</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sets.html">setdiff</a></span><span class="op">(</span><span class="va">alpha_divs</span>, <span class="va">removed_feats</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="preprocess-for-regression-task" class="level3 page-columns page-full" data-number="24.3.2"><h3 data-number="24.3.2" class="anchored" data-anchor-id="preprocess-for-regression-task">
<span class="header-section-number">24.3.2</span> Preprocess for regression task</h3>
<p>Similar to the code shown above, the following code shows how to preprocess our dataset. This time, however, we are interested in a regression task.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preprocess data for regression task</span></span>
<span><span class="va">tse</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/preprocess_data.html">preprocess_data</a></span><span class="op">(</span></span>
<span>    dataset <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"BMI"</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"relabundance"</span>,</span>
<span>    name <span class="op">=</span> <span class="st">"prep_regression"</span>,</span>
<span>    col.var <span class="op">=</span> <span class="va">alpha_divs</span>, <span class="co"># preprocess these metadata variables too</span></span>
<span>    remove_var <span class="op">=</span> <span class="st">"zv"</span>,</span>
<span>    collapse_corr_feats <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    group_neg_corr <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Identify the discarded features (that won't be used as predictors)</span></span>
<span><span class="va">prep_regression</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/altExps.html">altExp</a></span><span class="op">(</span><span class="va">tse</span>, <span class="st">"prep_regression"</span><span class="op">)</span></span>
<span><span class="va">removed_feats</span> <span class="op">&lt;-</span> <span class="fu">metadata</span><span class="op">(</span><span class="va">prep_regression</span><span class="op">)</span><span class="op">[[</span><span class="st">"removed_feats"</span><span class="op">]</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># If any alpha diversity index was removed, it will be discarded</span></span>
<span><span class="co"># from the predictors</span></span>
<span><span class="va">alpha_divs_regression</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sets.html">setdiff</a></span><span class="op">(</span><span class="va">alpha_divs</span>, <span class="va">removed_feats</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that the preprocessed dataset for the classification and regression tasks are stored within the ‘tse’ object, under the ‘altExp’ called ‘prep_classification’ and ‘prep_regression’, respectively.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Preprocessing strategies impact the performance of ML models.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Although microbiome data <strong>is</strong> compositional, proportion-based transformations —such as relative abundance or Hellinger— or even simpler approaches often outperform compositional transformations like CLR when building supervised ML models <span class="citation" data-cites="yerke2024">(<a href="#ref-yerke2024" role="doc-biblioref">Yerke, Fry Brumit, and Fodor 2024</a>)</span>. The authors note that the impact of the chosen transformations decreases as the signal-to-noise ratio increases. In other words, the more distinct the conditions we aim to classify, the less influence preprocessing transformations will have on model performance.</p>
<p>The aforementioned paper described the effect in both regression and classification tasks. A similar observations have also been done in other papers where they extensively compared different transformations in microbiome classification data <span class="citation" data-cites="Karwowska2025 Giliberti2022">(<a href="#ref-Karwowska2025" role="doc-biblioref">Karwowska et al. 2025</a>; <a href="#ref-Giliberti2022" role="doc-biblioref">Giliberti 2022</a>)</span>. These papers suggest presence/absence being the preferred approach in supervised ML applications. Even though the papers benchmarked transformations only in classification, their findings are likely applicable to regression as well.</p>
<p>These studies were conducted with stool samples which contain many sources of biases as they serve as proxy for our main interest: the gut microbiome. This can explain why the simpler approaches are more robust and reproducible. Moreover, in addition to improving model performance, proportion or presence/absence-based transformations are more intuitive and therefore easier to interpret.</p>
<p>Given this, it is worth exploring different preprocessing approaches. The <code>preprocess_data</code> function from the <em><a href="https://CRAN.R-project.org/package=mikropml">mikropml</a></em> package supports a variety of strategies described <a href="https://www.schlosslab.org/mikropml/reference/preprocess_data.html">here</a>. For a discussion in transformations methods, see <a href="transformation.html" class="quarto-xref"><span>Chapter 11</span></a>.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-Giliberti2022" class="csl-entry" role="listitem">
Giliberti, Sara AND Mauriello, Renato AND Cavaliere. 2022. <span>“Host Phenotype Classification from Human Microbiome Data Is Mainly Driven by the Presence of Microbial Taxa.”</span> <em>PLOS Computational Biology</em> 18 (4): 1–22. <a href="https://doi.org/10.1371/journal.pcbi.1010066">https://doi.org/10.1371/journal.pcbi.1010066</a>.
</div></div><div class="no-row-height column-margin column-container"><div id="ref-Karwowska2025" class="csl-entry" role="listitem">
Karwowska, Zuzanna, Oliver Aasmets, Mait Metspalu, Andres Metspalu, Lili Milani, Tõnu Esko, Tomasz Kosciolek, and Elin Org. 2025. <span>“Effects of Data Transformation and Model Selection on Feature Importance in Microbiome Classification Data.”</span> <em>Microbiome</em> 13 (1). <a href="https://doi.org/10.1186/s40168-024-01996-6">https://doi.org/10.1186/s40168-024-01996-6</a>.
</div></div><div class="no-row-height column-margin column-container"><div id="ref-yerke2024" class="csl-entry" role="listitem">
Yerke, Aaron, Daisy Fry Brumit, and Anthony A. Fodor. 2024. <span>“Proportion-Based Normalizations Outperform Compositional Data Transformations in Machine Learning Applications.”</span> <em>Microbiome</em> 12 (1): 45. <a href="https://doi.org/10.1186/s40168-023-01747-z">https://doi.org/10.1186/s40168-023-01747-z</a>.
</div></div></section></section><section id="model-training" class="level2 page-columns page-full" data-number="24.4"><h2 data-number="24.4" class="anchored" data-anchor-id="model-training">
<span class="header-section-number">24.4</span> Model training</h2>
<p>Now we can deploy supervised ML models on the preprocessed data. In this section, two algorithms will be covered:</p>
<ul>
<li>Random Forest</li>
<li>XGBoost</li>
</ul>
<p>These are within the most used supervised ML methods in the microbiome field. Possible reasons are that they can be used for classification and regression tasks, and that they show a good balance between performance and interpretability. Since the focus of this book is the implementation and interpretation of these models, other resources are suggested for an introduction to the mathematical underpinnings of these —and other— models <span class="citation" data-cites="james2013_ISLR">(<a href="#ref-james2013_ISLR" role="doc-biblioref">Gareth James 2013</a>)</span>.</p>
<div class="no-row-height column-margin column-container"><div id="ref-james2013_ISLR" class="csl-entry" role="listitem">
Gareth James, Robert Tibshirani, Trevor Hastie. 2013. <em>An Introduction to Statistical Learning: With Applications in <span>R</span></em>. New York : Springer, [2013] ©2013. <a href="https://search.library.wisc.edu/catalog/9910207152902121">https://search.library.wisc.edu/catalog/9910207152902121</a>.
</div></div><section id="random-forest" class="level3" data-number="24.4.1"><h3 data-number="24.4.1" class="anchored" data-anchor-id="random-forest">
<span class="header-section-number">24.4.1</span> Random forest</h3>
<p>Random Forests (RF) is an ensemble algorithm. That means that RF deploys and combines the outputs of multiple decision trees through majority voting or averaging the predicted numerical outcome. Since each tree is trained on a random subset of the data and features, RF reduces overfitting and enhance generalization to new data.</p>
<p>When applied to classification problems, each tree predicts the class of an observation (e.g., healthy or T2D) based on the values of the features (e.g., taxonomic). Each tree finds the best split of the data by reducing how mixed the classes are, often using metrics like entropy or Gini impurity.</p>
<p>Below, the RF algorithm is used for a classification task:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Train random forest for classification</span></span>
<span><span class="va">rf_classification</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/run_ml.html">run_ml</a></span><span class="op">(</span></span>
<span>    dataset <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    method <span class="op">=</span> <span class="st">"rf"</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"disease"</span>,</span>
<span>    altexp <span class="op">=</span> <span class="st">"prep_classification"</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"prep_classification"</span>,</span>
<span>    col.var <span class="op">=</span> <span class="va">alpha_divs_classification</span>, <span class="co"># use these variables as predictors too</span></span>
<span>    seed <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    kfold <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    cv_times <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    training_frac <span class="op">=</span> <span class="fl">.8</span>,</span>
<span>    find_feature_importance <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For regression tasks, each tree predicts a numerical outcome (e.g., BMI) based on the values of the features (e.g., taxonomic). Each tree split the data to minimize the difference between predicted and real (observed) values, often using metrics like mean squared error (MSE). One strength of RF is that it can learn non-linear patterns in the data that simpler regression algorithms might not capture.</p>
<p>Regarding its implementation, note that just by changing the outcome from a categorical to a continuous variable, RF models can now be used in regression tasks:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Train random forest for regression</span></span>
<span><span class="va">rf_regression</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/run_ml.html">run_ml</a></span><span class="op">(</span></span>
<span>    dataset <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    method <span class="op">=</span> <span class="st">"rf"</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"BMI"</span>,</span>
<span>    altexp <span class="op">=</span> <span class="st">"prep_regression"</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"prep_regression"</span>,</span>
<span>    col.var <span class="op">=</span> <span class="va">alpha_divs_regression</span>, <span class="co"># use these variables as predictors too</span></span>
<span>    seed <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    kfold <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    cv_times <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    training_frac <span class="op">=</span> <span class="fl">.8</span>,</span>
<span>    find_feature_importance <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="xgboost" class="level3 page-columns page-full" data-number="24.4.2"><h3 data-number="24.4.2" class="anchored" data-anchor-id="xgboost">
<span class="header-section-number">24.4.2</span> XGBoost</h3>
<p>Extreme Gradient Boosting (XGBoost) is another ensemble algorithm where decision trees are sequentially built. In this strategy, each new tree improves the performance of the previous.</p>
<p>When applied to classification, each tree predicts the class of an observation (e.g., healthy or T2D) based on feature values (e.g., taxonomic). However, instead of ‘voting’ like in Random Forest, XGBoost improves the performance by assigning higher weights (or penalties) to missclassified observations.</p>
<p>It must be noted that XGBoost is a more complex model usually described as one of the best performing models for tabular data <span class="citation" data-cites="SHWARTZZIV202284">(<a href="#ref-SHWARTZZIV202284" role="doc-biblioref">Shwartz-Ziv and Armon 2022</a>)</span>, such as the count tables used in microbiome data analysis.</p>
<div class="no-row-height column-margin column-container"><div id="ref-SHWARTZZIV202284" class="csl-entry" role="listitem">
Shwartz-Ziv, Ravid, and Amitai Armon. 2022. <span>“Tabular Data: Deep Learning Is Not All You Need.”</span> <em>Information Fusion</em> 81: 84–90. https://doi.org/<a href="https://doi.org/10.1016/j.inffus.2021.11.011">https://doi.org/10.1016/j.inffus.2021.11.011</a>.
</div></div><div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Train XGBoost for classification</span></span>
<span><span class="va">xgb</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/run_ml.html">run_ml</a></span><span class="op">(</span></span>
<span>    dataset <span class="op">=</span> <span class="va">tse</span>,</span>
<span>    method <span class="op">=</span> <span class="st">"xgbTree"</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"disease"</span>,</span>
<span>    altexp <span class="op">=</span> <span class="st">"prep_classification"</span>,</span>
<span>    assay.type <span class="op">=</span> <span class="st">"prep_classification"</span>,</span>
<span>    col.var <span class="op">=</span> <span class="va">alpha_divs_classification</span>, <span class="co"># use these variables as predictors too</span></span>
<span>    seed <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    kfold <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    cv_times <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    training_frac <span class="op">=</span> <span class="fl">.8</span>,</span>
<span>    find_feature_importance <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Although not demonstrated in this chapter, XGBoost can be used in regressions tasks using similar code to the one shown above. The only difference will be the outcome variable selected. See the RF example as a reference.</p>
</section></section><section id="model-performance-metrics" class="level2 page-columns page-full" data-number="24.5"><h2 data-number="24.5" class="anchored" data-anchor-id="model-performance-metrics">
<span class="header-section-number">24.5</span> Model performance metrics</h2>
<p>Under the hood, the function <code>run_ml</code> from the <em><a href="https://CRAN.R-project.org/package=mikropml">mikropml</a></em> package generates a default 80/20 split of the data to train and test a model of interest. That means that after the model is trained (i.e., learns patterns) in 80% of the data, the remaining 20% of data (not seen by our model in the training) is used to assess how well our model can generalize the patterns it learned to new data.</p>
<p>Therefore, the goals of this section are: to discuss different metrics used to assess the performance of the model, to compare metrics from two models used in the classification of the same observations, and to contrasts the results of these models with previous analyses in the published literature.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: Assess model performance with multiple data splits
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice that the function <code>run_ml</code> performs only one 80/20 split. Thus, the output metrics represent the performance of the model in one of multiple splitting scenarios. However, researchers are often interested in generating multiple splits, calculate the performance of the models trained on each split, and then look at the variability across iterations. This gives a more accurate assessment of the model’s performance. That approach is discussed in the <a href="https://www.schlosslab.org/mikropml/articles/parallel.html">documentation</a> of <em><a href="https://CRAN.R-project.org/package=mikropml">mikropml</a></em>.</p>
</div>
</div>
<section id="classification-metrics" class="level3 page-columns page-full" data-number="24.5.1"><h3 data-number="24.5.1" class="anchored" data-anchor-id="classification-metrics">
<span class="header-section-number">24.5.1</span> Classification metrics</h3>
<p>Two models (RF and XGBoost) were used to perform a classification task in the same microbiome dataset. Since both were used in classification, the type of performance metrics are the same:</p>
<p>Metrics of the RF model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># RF performance in classification tasks</span></span>
<span><span class="va">rf_classification</span><span class="op">[[</span><span class="st">"performance"</span><span class="op">]</span><span class="op">]</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 2%">
</colgroup>
<thead><tr class="header">
<th style="text-align: right;">cv_metric_AUC</th>
<th style="text-align: right;">logLoss</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">prAUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Kappa</th>
<th style="text-align: right;">F1</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
<th style="text-align: right;">Pos_Pred_Value</th>
<th style="text-align: right;">Neg_Pred_Value</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">Detection_Rate</th>
<th style="text-align: right;">Balanced_Accuracy</th>
<th style="text-align: left;">method</th>
<th style="text-align: right;">seed</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">0.7532</td>
<td style="text-align: right;">0.6497</td>
<td style="text-align: right;">0.6661</td>
<td style="text-align: right;">0.6383</td>
<td style="text-align: right;">0.6176</td>
<td style="text-align: right;">0.2353</td>
<td style="text-align: right;">0.6061</td>
<td style="text-align: right;">0.5882</td>
<td style="text-align: right;">0.6471</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: right;">0.6111</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: right;">0.5882</td>
<td style="text-align: right;">0.2941</td>
<td style="text-align: right;">0.6176</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">1</td>
</tr></tbody>
</table>
</div>
</div>
<p>Metrics of the XGBoost model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># XGBoost performance in classification tasks</span></span>
<span><span class="va">xgb</span><span class="op">[[</span><span class="st">"performance"</span><span class="op">]</span><span class="op">]</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A common metric to quickly assess model performance in binary classification tasks is the area under the receiver operator characteristic curve ‘AUC’. Notice that the result tables include two types of AUC metrics: <code>cv_metric_AUC</code>, which represents AUC for the 80% of data used in training, and <code>AUC</code>, which is the AUC for the 20% used in testing. Thus, results where the performance of the model in the train set highly exceeds its performance in the test set suggest overfiting, meaning that the model fails to generalize to new data. Notice, however, that small drops of model’s performance in the test compared to the train data are expected and thus shouldn’t be a concern.</p>
<p>Now let’s take a look at the results. First, notice that AUC values suggest a relatively good performance considering that predicting outcomes based on complex microbiome data is typically a challenging task. In addition, notice that the performance of RF and XGBoost are similar (RF AUC = 0.6661 and XGBoost AUC = <code>{r}# round(xgb[["performance"]][["AUC"]], 4)</code>). This illustrates an important point in ML: sometimes simpler models can perform as good as more complex ones. Thus, it is often a good idea to deploy different models and compare their performance on the same task.</p>
<p>Now let’s interpret our results at the light of previous research. In the largest multi-cohort analysis of gut microbiome associations with T2D published to date <span class="citation" data-cites="mei2024_t2d">(<a href="#ref-mei2024_t2d" role="doc-biblioref">Mei et al. 2024</a>)</span>, authors report similar AUC values to ours when training RF models to discriminate healthy participants and T2D patients using microbiome and anthropometric variables like age, sex and BMI. Interestingly, they included the study we are working with in their analysis. Notice their reported AUC of 0.74, which is very close to ours. This further validates the potential of the gut microbiome to discriminate between healthy individuals and T2D patients.</p>
<div class="no-row-height column-margin column-container"></div><p>Although the tasks we addressed required binomial classification (i.e., classify sampples either as patients or controls), some research questions will require the classification of observations in more than just two groups, a task known as multiclass classification. For instance, we may have been interested in classifying patients as (1) healthy individuals, (2) T2D patients with obesity, and (3) T2D patients without obesity by integrating BMI information. In such cases, metrics like AUC (developed for binary classification) can be generalized. This metric is known as multiclass AUC, or One-vs-Rest AUC. This approach evaluates how well each class is distinguished from the others, enabling the assessment of model performance in multiclass problems. Multiclass classification can be implemented with <code>run_ml</code> too, as described <a href="https://www.schlosslab.org/mikropml/articles/introduction.html?q=multiclass#multiclass-data">here</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: Always use multiple performance metrics
</div>
</div>
<div class="callout-body-container callout-body">
<p>Regardless of the type of classification task performed, it is often desirable to look at different metrics to accurately assess the model’s performance. This is particularly relevant in cases where classes are imbalanced. Suppose a dataset consists of 95% healthy individuals, and only 5% T2D patients. In such a case, a model can easily achieve 95% accuracy by just predicting (labelling) all samples as healthy, despite being useless for the classification of T2D patients.</p>
<p>This is an extreme case and hopefully we won’t encounter such situations. However, it highlights that class imbalance can lead to misleading interpretations of performance metrics like accuracy and AUC. Thus, when dealing with imbalanced classes, other metrics like F1-score and the area under the precision recall curve (prAUC), might be more appropriate.</p>
<p>In addition to relying in other performance metrics, different strategies for handling class imbalance datasets have been discussed <span class="citation" data-cites="Papoutsoglou2023">(<a href="#ref-Papoutsoglou2023" role="doc-biblioref">Papoutsoglou et al. 2023</a>)</span> and applied <span class="citation" data-cites="Diez2022">(<a href="#ref-Diez2022" role="doc-biblioref">Diez Lopez et al. 2022</a>)</span> in microbiome data analysis before.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-Diez2022" class="csl-entry" role="listitem">
Diez Lopez, Celia, Diego Montiel Gonzalez, Athina Vidaki, and Manfred Kayser. 2022. <span>“Prediction of Smoking Habits from Class-Imbalanced Saliva Microbiome Data Using Data Augmentation and Machine Learning.”</span> <em>Frontiers in Microbiology</em> 13. <a href="https://doi.org/10.3389/fmicb.2022.886201">https://doi.org/10.3389/fmicb.2022.886201</a>.
</div></div><div class="no-row-height column-margin column-container"><div id="ref-Papoutsoglou2023" class="csl-entry" role="listitem">
Papoutsoglou, Georgios, Sonia Tarazona, Marta B. Lopes, Thomas Klammsteiner, Eliana Ibrahimi, Julia Eckenberger, Pierfrancesco Novielli, et al. 2023. <span>“Machine Learning Approaches in Microbiome Research: Challenges and Best Practices.”</span> <em>Frontiers in Microbiology</em> 14. <a href="https://doi.org/10.3389/fmicb.2023.1261889">https://doi.org/10.3389/fmicb.2023.1261889</a>.
</div></div></section><section id="regression-metrics" class="level3" data-number="24.5.2"><h3 data-number="24.5.2" class="anchored" data-anchor-id="regression-metrics">
<span class="header-section-number">24.5.2</span> Regression metrics</h3>
<p>When RF are used in regression tasks, the performance metrics are different to what was discussed for classifications.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># RF performance in regression tasks</span></span>
<span><span class="va">rf_regression</span><span class="op">[[</span><span class="st">"performance"</span><span class="op">]</span><span class="op">]</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">cv_metric_RMSE</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: left;">method</th>
<th style="text-align: right;">seed</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">3.382</td>
<td style="text-align: right;">3.886</td>
<td style="text-align: right;">0.0231</td>
<td style="text-align: right;">3.043</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">1</td>
</tr></tbody>
</table>
</div>
</div>
<p>A commonly used metric to quickly assess model performance in regression tasks is the root mean square error (RMSE). As its name suggests, this metric is just the root of the mean squared difference between the observed and predicted values of the outcome variable (patient’s BMI in this example).</p>
<p>Similarly to AUC in classification, the results table include two types of RMSE metrics: <code>cv_metric_RMSE</code>, which represents RMSE for the 80% of data used in training, and <code>RMSE</code>, which is the metric for the 20% used in testing. Notice, the small drop of model’s performance in the test (3.886) compared to the train (3.382) tests. As discussed in the classification results, big drops of model’s performance in the test compared to the train data are indicative of overfitting. However, in this case the drop in performance is small and thus it shouldn’t be a concern.</p>
</section></section><section id="visualizing-models-performance" class="level2 page-columns page-full" data-number="24.6"><h2 data-number="24.6" class="anchored" data-anchor-id="visualizing-models-performance">
<span class="header-section-number">24.6</span> Visualizing model’s performance</h2>
<p>We explored the different performance metrics used in classification and regression tasks. However, researchers are often interested in generating visual representations of the performance of their models. Thus, the goal of this section is to show code to create those visualizations, as well as providing insights in their interpretations.</p>
<section id="classification" class="level3 page-columns page-full" data-number="24.6.1"><h3 data-number="24.6.1" class="anchored" data-anchor-id="classification">
<span class="header-section-number">24.6.1</span> Classification</h3>
<p>The area under the receiver-operator characteristic (ROC) curve, also called ‘AUC’ was introduced before as common metric to assess model’s performance in binary classification tasks. As it name suggests, AUC is just the area under a curve. Since different ROC curves can have similar AUC, visualizing the curve can give complementary information.</p>
<p>Complementary to ROC curves, the precision-recall curves (PRC) are preferred in datasets with class imbalance, where AUC can be misleading, as discussed above.</p>
<p>The code below is used to calculate the metrics required to generate both curves for the two models generated (RF and XGBoost):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate RF model metrics required for plotting</span></span>
<span><span class="va">rf_senspec</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/sensspec.html">calc_model_sensspec</a></span><span class="op">(</span></span>
<span>    <span class="va">rf_classification</span><span class="op">[[</span><span class="st">"trained_model"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    <span class="va">rf_classification</span><span class="op">[[</span><span class="st">"test_data"</span><span class="op">]</span><span class="op">]</span></span>
<span><span class="op">)</span></span>
<span><span class="co"># Add model label to data</span></span>
<span><span class="va">rf_senspec</span><span class="op">$</span><span class="va">model</span> <span class="op">&lt;-</span> <span class="st">"rf"</span></span>
<span></span>
<span><span class="co"># # Calculate XGBoost model metrics required for plotting</span></span>
<span><span class="co"># xgb_senspec &lt;- calc_model_sensspec(</span></span>
<span><span class="co">#     xgb[["trained_model"]],</span></span>
<span><span class="co">#     xgb[["test_data"]]</span></span>
<span><span class="co"># )</span></span>
<span><span class="co"># # Add model label to data</span></span>
<span><span class="co"># xgb_senspec$model &lt;- "XGBoost"</span></span>
<span></span>
<span><span class="co"># Combine model metrics</span></span>
<span><span class="va">senspec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">rf_senspec</span><span class="op">)</span><span class="co">#, xgb_senspec)</span></span>
<span></span>
<span><span class="co"># Inspect part of the output</span></span>
<span><span class="va">senspec</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">T2D</th>
<th style="text-align: right;">healthy</th>
<th style="text-align: left;">actual</th>
<th style="text-align: right;">tp</th>
<th style="text-align: right;">fp</th>
<th style="text-align: right;">sensitivity</th>
<th style="text-align: right;">fpr</th>
<th style="text-align: right;">specificity</th>
<th style="text-align: right;">precision</th>
<th style="text-align: left;">model</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T2D-059</td>
<td style="text-align: right;">0.806</td>
<td style="text-align: right;">0.194</td>
<td style="text-align: left;">T2D</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: left;">rf</td>
</tr>
<tr class="even">
<td style="text-align: left;">CON-079</td>
<td style="text-align: right;">0.788</td>
<td style="text-align: right;">0.212</td>
<td style="text-align: left;">healthy</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.9706</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: left;">rf</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T2D-104</td>
<td style="text-align: right;">0.768</td>
<td style="text-align: right;">0.232</td>
<td style="text-align: left;">T2D</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0588</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.9706</td>
<td style="text-align: right;">0.6667</td>
<td style="text-align: left;">rf</td>
</tr>
<tr class="even">
<td style="text-align: left;">T2D-078</td>
<td style="text-align: right;">0.760</td>
<td style="text-align: right;">0.240</td>
<td style="text-align: left;">T2D</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0882</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.9706</td>
<td style="text-align: right;">0.7500</td>
<td style="text-align: left;">rf</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T2D-088</td>
<td style="text-align: right;">0.760</td>
<td style="text-align: right;">0.240</td>
<td style="text-align: left;">T2D</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1176</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.9706</td>
<td style="text-align: right;">0.8000</td>
<td style="text-align: left;">rf</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOF010</td>
<td style="text-align: right;">0.714</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: left;">T2D</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1471</td>
<td style="text-align: right;">0.0294</td>
<td style="text-align: right;">0.9706</td>
<td style="text-align: right;">0.8333</td>
<td style="text-align: left;">rf</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The metrics ‘Sensitivity’ and ‘Specificity’ are used in ROC curves, and ‘Sensitivity’ and ‘Precision’ are used in PRC curves. Note that ‘Precision’ and ‘Recall’ are the same metric. While the term ‘Precision’ is preferred in the biomedical literature, ‘Recall’ is more prevalent in other fields.</p>
<p>The code below generates the ROC and PRC curves of both models and shows them side by side:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 1. Plot the ROC curve of each model</span></span>
<span><span class="va">roc_p</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">senspec</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_path</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">fpr</span>, y <span class="op">=</span> <span class="va">sensitivity</span>, color <span class="op">=</span> <span class="va">model</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># 1.1 Add line representing 'random guess' performance</span></span>
<span><span class="va">roc_p</span> <span class="op">&lt;-</span> <span class="va">roc_p</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_abline</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey30"</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span></span>
<span><span class="co"># 1.2 Add axis titles and custom theme</span></span>
<span><span class="va">roc_p</span> <span class="op">&lt;-</span> <span class="va">roc_p</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"FPR or (1 - Specificity)"</span>, y <span class="op">=</span> <span class="st">"Sensitivity"</span>, title <span class="op">=</span> <span class="st">"ROC"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># 2. Plot the PRC curve of each model</span></span>
<span><span class="va">prc_p</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">senspec</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_path</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">sensitivity</span>, y <span class="op">=</span> <span class="va">precision</span>, color <span class="op">=</span> <span class="va">model</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># 2.1 Add line representing 'random guess' performance</span></span>
<span><span class="va">prc_p</span> <span class="op">&lt;-</span> <span class="va">prc_p</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_hline</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey30"</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span>, yintercept <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span><span class="co"># 2.2 Add axis titles and custom theme</span></span>
<span><span class="va">prc_p</span> <span class="op">&lt;-</span> <span class="va">prc_p</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Recall or Sensitivity"</span>, y <span class="op">=</span> <span class="st">"Precision"</span>, title <span class="op">=</span> <span class="st">"PRC"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># 3. Plot ROC and PRC side by side</span></span>
<span><span class="va">roc_p</span> <span class="op">+</span> <span class="va">prc_p</span> <span class="op">+</span> <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>guides <span class="op">=</span> <span class="st">"collect"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="machine_learning_files/figure-html/6.2 - plot ROC and PRC-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Before describing the plots and their meaning, it is worth noting that the ROC curves of both models resembles the curve presented in the article where this dataset was first analysed <span class="citation" data-cites="qin2012_t2d">(<a href="#ref-qin2012_t2d" role="doc-biblioref">Qin et al. 2012</a>)</span> (see Figure 4B). Interestingly, authors used other supervised ML algorithm, and it was trained in a set of 50 microbiome genes (instead of taxonomic features and alpha diversity metrics, as we did). However, it is interesting that concordant AUCs and ROC curves shapes were obtained using different microbiome-derived information.</p>
<div class="no-row-height column-margin column-container"></div><p>Regarding our figures, note the dashed grey lines in both plots representing the expected performance of a model that is classifying samples randomly. Therefore, the greater the distance between that reference and the line representing our model’s performance, the better. Thus, perfect performance will be achieve when the line is the farthest from that reference.</p>
<p>In our example, a model with perfect performance is such that, by learning patterns from the microbiome data, it can correctly identify T2D patients with perfect sensitivity (i.e., all T2D patients are classified as such) while maintaining a false positive rate (FPR) of 0 (i.e., no healthy individual is misclassified as T2D). In the ROC plot, this means the model consistently achieves a Sensitivity of 1 and a FPR of 0, pushing the curve towards the top left corner.</p>
<p>In terms of the PRC plot, the perfect model would consistently achieve a Recall and Precision of 1, pushing the curve towards the top right corner. That, in turn, would mean that the model has perfect Sensitivity (i.e., all T2D patients are classified as such), while maintaining a perfect Precision (i.e., every individual classified as T2D is actually a T2D patient).</p>
<p>Finally, note that the ROC curves of RF and XGBoost have a similar shape. This suggests a similar performance in classifying T2D patients. This isn’t surprising as the AUC of both models were very similar too (RF AUC = 0.6661 and XGBoost AUC = <code>{r}# round(xgb[["performance"]][["AUC"]], 4)</code>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Visualization of multiclass ROC curves
</div>
</div>
<div class="callout-body-container callout-body">
<p>It was discussed above that ROC curves (and AUCs) can be extended to multiclass classification tasks. One example of such approach is this article <span class="citation" data-cites="su2022_multiclassML">(<a href="#ref-su2022_multiclassML" role="doc-biblioref">Su et al. 2022</a>)</span> where authors used gut microbiome data to train different classification supervised ML algorithms to discriminate between patients of 9 different diseases. Notice that the visualization of multiclass ROC curves can be achieved in a similar way to what was described in this chapter. In addition, the R package <em><a href="https://CRAN.R-project.org/package=pROC">pROC</a></em> provides handy functions to build multiclass visualizations.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-su2022_multiclassML" class="csl-entry" role="listitem">
Su, Qi, Qin Liu, Raphaela Iris Lau, Jingwan Zhang, Zhilu Xu, Yun Kit Yeoh, Thomas W. H. Leung, et al. 2022. <span>“Faecal Microbiome-Based Machine Learning for Multi-Class Disease Diagnosis.”</span> <em><span>Nature Communications</span></em> 13 (1). <a href="https://doi.org/10.1038/s41467-022-34405-3">https://doi.org/10.1038/s41467-022-34405-3</a>.
</div></div></section><section id="regression" class="level3" data-number="24.6.2"><h3 data-number="24.6.2" class="anchored" data-anchor-id="regression">
<span class="header-section-number">24.6.2</span> Regression</h3>
<p>In this chapter RF was used to learn patterns in the gut microbiome to predict the BMI of the participants. The most used diagnostic visualization of model’s performance is to compare observed against predicted BMI values.</p>
<p>The code below is used to generate that plot using the observations in the test data.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Get the test set: data not used in training the model</span></span>
<span><span class="va">test_data</span> <span class="op">&lt;-</span> <span class="va">rf_regression</span><span class="op">[[</span><span class="st">"test_data"</span><span class="op">]</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Get the trained model</span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="va">rf_regression</span><span class="op">[[</span><span class="st">"trained_model"</span><span class="op">]</span><span class="op">]</span><span class="op">[[</span><span class="st">"finalModel"</span><span class="op">]</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Use the model to predict BMI values in the test set</span></span>
<span><span class="va">pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span>, <span class="va">test_data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Add predicted BMI values to the test dataset</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">pred</span> <span class="op">&lt;-</span> <span class="va">pred</span></span>
<span><span class="co"># Add diagnosis status to test data.</span></span>
<span><span class="co"># This variable was created when preprocessing for classification</span></span>
<span><span class="va">ids</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">)</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">disease</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">colData</a></span><span class="op">(</span><span class="va">tse</span><span class="op">)</span><span class="op">[</span><span class="va">ids</span>, <span class="st">"disease"</span><span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">disease</span><span class="op">)</span></span>
<span><span class="co">##  </span></span>
<span><span class="co">##      T2D healthy </span></span>
<span><span class="co">##       36      32</span></span>
<span></span>
<span><span class="co"># Plot actual (y-axis) vs predicted (x-axis) BMI values</span></span>
<span><span class="va">obs_vs_pred</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">test_data</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">pred</span>, y <span class="op">=</span> <span class="va">BMI</span>, color <span class="op">=</span> <span class="va">disease</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="co"># Add line showing perfect prediction</span></span>
<span><span class="va">obs_vs_pred</span> <span class="op">&lt;-</span> <span class="va">obs_vs_pred</span> <span class="op">+</span> <span class="fu">geom_abline</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey30"</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span></span>
<span><span class="co"># Make axes of same scale</span></span>
<span><span class="va">obs_vs_pred</span> <span class="op">&lt;-</span> <span class="va">obs_vs_pred</span> <span class="op">+</span> <span class="fu">coord_equal</span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">17</span>, <span class="fl">30</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">17</span>, <span class="fl">30</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Custom axes titles</span></span>
<span><span class="va">obs_vs_pred</span> <span class="op">&lt;-</span> <span class="va">obs_vs_pred</span> <span class="op">+</span> <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Predicted BMI"</span>, y <span class="op">=</span> <span class="st">"Observed BMI"</span><span class="op">)</span></span>
<span><span class="co"># Add custom theme and visualize the plot</span></span>
<span><span class="va">obs_vs_pred</span> <span class="op">+</span> <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="machine_learning_files/figure-html/6.2 - plot predicted vs observed-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The dashed grey line in the plot above represents a perfect correlation between the observed and the model-predicted BMI values of each participant. Thus, the line indicates perfect performance of the model. We can see that while the predictions are around the mean BMI (close to 24), the observed values range approximately between 17 and 38, showing poor correlation between observed and predicted BMI values. Note that both groups show a similar spread in BMI.</p>
<p>This plot clearly indicates a poor performance of our model. This usually means that either the gut microbiome is not related to BMI, making it impossible for the model to use microbiome patterns to predict it, or that our model is overfitted. Since the RMSE for training (3.3819) and test (3.886) data are similar, we may conclude that gut microbiome composition is not informative of BMI.</p>
<p>This illustrate another important aspect of supervised ML. Regardless of the complexity of the models deployed, their predictive performance depends in their ability to learn meaningful patterns from the data. If such patterns don’t exist it would be impossible for the model to make accurate predictions. This is most likely what happened in this regression task. Notice that this can certainly happen in classification tasks too.</p>
</section></section><section id="model-interpretation" class="level2 page-columns page-full" data-number="24.7"><h2 data-number="24.7" class="anchored" data-anchor-id="model-interpretation">
<span class="header-section-number">24.7</span> Model interpretation</h2>
<p>Besides the performance of the model, researchers are often interested in understanding what are the features that are affecting the model’s performance, a property of ML models called interpretability.</p>
<p>ML models have different degrees of interpretability. One way to understand how different features (e.g., taxonomic identity) affect model’s performance is by randomly permuting the values of that feature across samples and then evaluating the amount of change in a performance metric.</p>
<p>For simplicity, the code below shows how to determine feature importance only with the RF model trained for classification. However, minimal changes are required to determine feature importance for other models built in this chapter, like the XGBoost model used in classification or the RF model used in regression.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># estimate features importance</span></span>
<span><span class="va">feat_imp</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://www.schlosslab.org/mikropml/reference/get_feature_importance.html">get_feature_importance</a></span><span class="op">(</span></span>
<span>    trained_model <span class="op">=</span> <span class="va">rf_classification</span><span class="op">[[</span><span class="st">"trained_model"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    test_data <span class="op">=</span> <span class="va">rf_classification</span><span class="op">[[</span><span class="st">"test_data"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    outcome_colname <span class="op">=</span> <span class="st">"disease"</span>,</span>
<span>    perf_metric_function <span class="op">=</span> <span class="va">multiClassSummary</span>,</span>
<span>    perf_metric_name <span class="op">=</span> <span class="st">"AUC"</span>,</span>
<span>    class_probs <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    method <span class="op">=</span> <span class="st">"rf"</span>,</span>
<span>    seed <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    nperms <span class="op">=</span> <span class="fl">5</span> <span class="co"># 1/20 of default to speed calculations up</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Identify the 10 most important features</span></span>
<span><span class="va">ordered_features</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">feat_imp</span><span class="op">$</span><span class="va">perf_metric_diff</span>, decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">ordered_features</span> <span class="op">&lt;-</span> <span class="va">ordered_features</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Retain only those features</span></span>
<span><span class="va">feat_imp</span> <span class="op">&lt;-</span> <span class="va">feat_imp</span><span class="op">[</span><span class="va">ordered_features</span>, <span class="op">]</span></span>
<span></span>
<span><span class="co"># Conver column 'feat' into a factor to fix its order in the plot</span></span>
<span><span class="va">feat_imp</span><span class="op">$</span><span class="va">feat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">feat_imp</span><span class="op">$</span><span class="va">feat</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rev.html">rev</a></span><span class="op">(</span><span class="va">feat_imp</span><span class="op">$</span><span class="va">feat</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot mean feature importance with 95% CI</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">feat_imp</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_col</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">perf_metric_diff</span>, y <span class="op">=</span> <span class="va">feat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Decrease in performance"</span>, y <span class="op">=</span> <span class="st">"Feature"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="machine_learning_files/figure-html/7 - Interpret the model-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the features with the highest effect on model’s performance. In other words, which features have most of the information required to differentiate between healthy participant and T2D patients. However, note that the differences in model performance are very close to zero, which indicates a small contribution of each taxonomic feature in allowing the model to distinguish between groups.</p>
<p>Interestingly, our results are coherent with what authors of the original analysis reported <span class="citation" data-cites="qin2012_t2d">(<a href="#ref-qin2012_t2d" role="doc-biblioref">Qin et al. 2012</a>)</span>. For instance, they mention that <em>F. prausnitzii</em> and <em>R. intestinalis</em> (also within our most relevant features) are important nodes in the co-occurrence network enriched in healthy participants. On the other hand, they report several <em>Clostridium</em> representatives enriched in the T2D patients (see Figure 2A). This taxonomic feature was also reported as having the largest differences in the mean abundances between groups <span class="citation" data-cites="mei2024_t2d">(<a href="#ref-mei2024_t2d" role="doc-biblioref">Mei et al. 2024</a>)</span> (see Figures 2A and 2B).</p>
<div class="no-row-height column-margin column-container"><div id="ref-qin2012_t2d" class="csl-entry" role="listitem">
Qin, Junjie, Yingrui Li, Zhiming Cai, Shenghui Li, Jianfeng Zhu, Fan Zhang, Suisha Liang, et al. 2012. <span>“A Metagenome-Wide Association Study of Gut Microbiota in Type 2 Diabetes.”</span> <em>Nature</em> 490: 55–60. <a href="https://doi.org/10.1038/nature11450">https://doi.org/10.1038/nature11450</a>.
</div><div id="ref-mei2024_t2d" class="csl-entry" role="listitem">
Mei, Zhendong, Fenglei Wang, Amrisha Bhosle, Danyue Dong, Raaj Mehta, Andrew Ghazi, Yancong Zhang, et al. 2024. <span>“Strain-Specific Gut Microbial Signatures in Type 2 Diabetes Identified in a Cross-Cohort Analysis of 8,117 Metagenomes.”</span> <em>Nature Medicine</em> 30 (8): 2265–76. <a href="https://doi.org/10.1038/s41591-024-03067-7">https://doi.org/10.1038/s41591-024-03067-7</a>.
</div></div><div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Important: A call to avoid oversimplifications
</div>
</div>
<div class="callout-body-container callout-body">
<p>Feature importance plots are often interpreted in the literature with a reductionist mindset. Thus, researchers often conclude that a single feature is responsible of a complex clinical output of interest. However, more often than not, microbes interact with one another, and thus the effect of a single taxonomic feature doesn’t always inform about ecosystem-level properties of the microbiome. It is important to bear that in mind when interpreting the results of our models.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercises
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Goal:</strong> After completing these exercises, you should be able to fit supervised machine learning model utilizing multi-assay data.</p>
<p><strong>Exercise 1: Supervised ML</strong></p>
<ol type="1">
<li><p>Load any of the example datasets mentioned in <a href="import.html#sec-example-data" class="quarto-xref"><span>Section 4.2</span></a>.</p></li>
<li><p>Observe <code>colData</code> and check that the metadata includes outcome variables that you want to model.</p></li>
<li><p>Visualize the selected outcome variable with a histogram or a bar plot. What is the distribution? If the distribution is biased, how can this affect the training of the model?</p></li>
<li><p>Apply CLR transformation.</p></li>
<li><p>Preprocess data by removing features with near-zero variance and by grouping correlated features.</p></li>
<li><p>Fit a random forest model with <code>find_feature_importance = TRUE</code>.</p></li>
<li><p>Visualize results. Do the model perform well by predicting the outcome with a high accuracy?</p></li>
<li><p>What features are the most important for predicting the outcome?</p></li>
</ol>
<p>Useful functions:</p>
<p><code><a href="https://rdrr.io/r/utils/data.html">utils::data()</a></code>, <code><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">SummarizedExperiment::colData()</a></code>, <code><a href="https://rdrr.io/pkg/miaViz/man/plotHistogram.html">miaViz::plotHistogram()</a></code>, <code><a href="https://rdrr.io/pkg/miaViz/man/plotHistogram.html">miaViz::plotBarplot()</a></code>, <code><a href="https://microbiome.github.io/mia/reference/getPrevalence.html">mia::subsetByPrevalent()</a></code>, <code><a href="https://microbiome.github.io/mia/reference/transformAssay.html">mia::transformAssay()</a></code>, <code><a href="http://www.schlosslab.org/mikropml/reference/preprocess_data.html">mikropml::preprocess_data()</a></code>, <code><a href="http://www.schlosslab.org/mikropml/reference/run_ml.html">mikropml::run_ml()</a></code>, <code><a href="http://www.schlosslab.org/mikropml/reference/plot_model_performance.html">mikropml::plot_model_performance()</a></code></p>
</div>
</div>



</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../pages/integrated_learner.html" class="pagination-link" aria-label="Multi-omics prediction and classification">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Multi-omics prediction and classification</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../pages/training.html" class="pagination-link" aria-label="Training">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Training</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="./">Orchestrating Microbiome Analysis with Bioconductor</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://github.com/js2264/BiocBook/">BiocBook</a> with <span class="emoji" data-emoji="heart">❤️</span></p>
</div>
  </div>
</footer>


</body></html>