project:
  type: book
  output-dir: docs
mathjax: null
metadata-files:
  - assets/_book.yml
  - assets/_website.yml
  - assets/_format.yml
  - assets/_knitr.yml
profiles:
  english:
    book:
      language: en
    project:
      input: "introductory_workflow.qmd" 

  german:
    book:
      language: de
    project:
      input: "introductory_workflow_dutch_version.qmd" 

  french:
    book:
      language: fr
    project:
      input: "introductory_workflow_french_version.qmd" 
      
default-profile: english