on:
  pull_request:
    branches:
      - devel
      - RELEASE_**
    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown"]
  workflow_dispatch:
  push:
name: Convert British English spelling into American English spelling
permissions: read-all
jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Convert from American English to British English
        run: bash .github/workflows/convert-british-to-american.sh
      - name: Commit and push changes
        # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Convert American English to British Enlish
