name: Link Checker

on:
  schedule:
    # Scheduled to run every day at midnight
    - cron: '35 10 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Markdown link checker
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          # Check links in Markdown files
          args: --verbose --no-progress *.md
