name: "Update cachix cache for Orchestrating Microbiome Analysis environment"

on:
  push:
    branches: [ master, main ]
jobs:
  r-update-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=https://github.com/rstats-on-nix/nixpkgs/archive/bc30fa6c937a4598564bd0fa7114cbad2a3554aa.tar.gz
  
    - uses: cachix/cachix-action@v14
      with:
        name: oma
        authToken: '${{ secrets.CACHIX_AUTH }}'
  
    - run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              nix-build --argstr system x86_64-linux
              nix-build --argstr system aarch64-linux
         else
              nix-build
         fi
        
    - run: nix-store -qR --include-outputs $(nix-instantiate ../../default.nix) | cachix push oma
    - run: nix-shell --run "echo OK"
