on:
  push:
    branches:
      - master
    paths:
      - '**.qmd'
      - '**.Rmd'
  workflow_dispatch:
permissions: write-all

name: renderbook-quarto

jobs:
  render-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
    
      - uses: quarto-dev/quarto-actions/setup@v2
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Install remotes Package
        run: Rscript -e 'install.packages("remotes")'
        
      - name: Install "bluster" Package
        run: Rscript -e 'remotes::install_version("bluster", version = "1.11.4")'

      - name: Render and Publish quarto
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Re-render bookdown documents" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

          
