name: renderbook-quarto

on:
  push:
    branches:
      - main  # Adjust this to your repository's main branch

jobs:
  render-book:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Dependencies
        run: |
          # Install 'rebook' package if it's required
          if ! R -e "library('rebook', logical.return = TRUE)" ; then
            R -e "install.packages('rebook')"
          fi
        shell: Rscript {0}

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish Quarto
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Re-render bookdown documents" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
